# Generated by Django 2.1.7 on 2019-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_messages_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='query',
        ),
    ]
