QUICK_HELP = 'Enter `@Enigma help` for help on using the Enigma.'

HELP_MESSAGE = ('Enigma usage:\n'
                '`@Enigma man <command-name>`\n'
                '`Provides man page for given command`\n\n'
                '`@Enigma ssh <username> <server-IP> <password> <command-name>`\n'
                '`Runs given command over SSH in network`\n\n'
                '`@Enigma sps start`\n'
                '`Starts the stone paper scissor game`\n'
                '`@Enigma sps <stone/paper/scissor>`\n'
                '`User can select either stone paper or scissor`\n\n'
                '`@Enigma hangman start`\n'
                '`Starts the hangman game`\n'
                '`@Enigma hangman <character>`\n'
                '`Unviels the character if it is present in the string`\n\n'
                '`@Enigma mind-game start`\n'
                '`Starts the mind-game`\n'
                '`@Enigma mind-game <x-coordinate> <y-coordinate>`\n'
                '`Unviels tile at position x and y (Zero indexed)`\n\n'
                '`@Enigma scrabble start`\n'
                '`Starts the scrabble game`\n'
                '`@Enigma scrabble <x-coordinate> <y-coordinate> <character>`\n'
                '`Places character at positon x y`\n\n'
                '`@Enigma todo start`\n'
                '`Initializes todo list`\n'
                '`@Enigma todo add <activity>`\n'
                '`Adds activity to todo list`\n'
                '`@Enigma todo remove <activity-id>`\n'
                '`Removes activity from todo list`\n'
                '`@Enigma todo list`\n'
                '`Displays todo list`\n\n'
                '`@Enigma calculator <expression>`\n'
                '`Performs arithmetic calculations`\n\n'
                '`@Enigma news <keyword>`\n'
                '`Displays latest news related to keywords`\n\n'
                '`@Enigma dictionary <word>`\n'
                '`Displays meaning of word`\n\n'
                '`@Enigma cricket`\n'
                '`Displays scores of latest cricket matches`\n\n'
                'Usage examples:\n'
                '* `@Enigma man cat`\n'
                '* `@Enigma ssh swap 192.168.0.7 ********* ls -l`\n'
                '* `@Enigma hangman start`\n'
                '* `@Enigma todo start`\n')
